import type { Metadata } from "next";
import { Telex, Jost } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/components/auth-provider";
import { DbInitializer } from "@/components/db-initializer";
import { Toaster } from "sonner";
import DevNav from "@/components/dev-nav";

const telex = Telex({
  variable: "--font-telex",
  subsets: ["latin"],
  weight: "400", // Telex only has 400 weight available
  display: "swap",
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  // Include all available Jost weights
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${telex.variable} ${jost.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <DbInitializer />
            <Toaster richColors position="top-right" />
            {children}
            {/* Dev navigation - only appears in development */}
            <DevNav />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
